name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        # Using 9.0.x to match your project configuration
        dotnet-version: 9.0.x

    - name: Install Playwright browsers
      # The path is now correct: it looks inside your project folder for the script
      run: pwsh ./MyPlaywrightTests/bin/Debug/net9.0/playwright.ps1 install --with-deps

    - name: Run tests
      # This command is simple and correct. It runs your project test.
      # The C# code in TracingTest.cs now automatically handles tracing.
      # We no longer need the --settings flag.
      run: dotnet test ./MyPlaywrightTests/MyPlaywrightTests.csproj

    - name: Upload trace files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-trace
        # This path correctly finds the trace file our C# code creates
        path: "**/TestResults/**/*.zip"
        retention-days: 7