name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # THE FIX IS HERE: We added the build step back in.
    - name: Build the project
      run: dotnet build ./MyPlaywrightTests/MyPlaywrightTests.csproj

    - name: Install Playwright browsers
      # This step will now succeed because the build created the necessary files.
      run: pwsh ./MyPlaywrightTests/bin/Debug/net9.0/playwright.ps1 install --with-deps

    - name: Run tests
      # This will run the tests and our C# code will handle the trace on failure.
      run: dotnet test ./MyPlaywrightTests/MyPlaywrightTests.csproj

    - name: Upload trace files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-trace
        path: "**/TestResults/**/*.zip"
        retention-days: 7