name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build the project
      # We do not need a path or working-directory. 
      # The checkout action places us in the folder with the .csproj file.
      run: dotnet build

    - name: Install Playwright browsers
      # The path is now simple because we are already in the correct folder.
      run: pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps

    - name: Run tests
      # Same as build, dotnet test will find the project automatically.
      # Our NUnit C# code will handle the trace on failure.
      run: dotnet test

    - name: Upload trace files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-trace
        # The TestResults folder will be created in the current directory.
        path: TestResults/**/*.zip
        retention-days: 7