name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Run tests and generate trace
      # This command tells GitHub to first move into your project folder...
      working-directory: ./MyPlaywrightTests
      # ...and then run the test command. It will now find the .runsettings file.
      run: dotnet test --settings MyPlaywright.runsettings

    - name: Upload trace files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-trace
        # The path must be relative to the repository root.
        path: ./MyPlaywrightTests/TestResults/**/*.zip
        retention-days: 7