name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build the project
      # We run this command from inside the correct folder.
      run: dotnet build
      working-directory: ./MyPlaywrightTests

    - name: Install Playwright browsers
      # This command also runs from inside the project folder.
      run: pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps
      working-directory: ./MyPlaywrightTests

    - name: Run tests
      # This also runs from inside the project folder.
      run: dotnet test
      working-directory: ./MyPlaywrightTests

    - name: Upload trace files on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-trace
        # The artifact path is relative to the repository root.
        path: ./MyPlaywrightTests/TestResults/**/*.zip
        retention-days: 7